services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green
    restart: unless-stopped

  app_blue:
    image: yimikaade/wonderful:latest
    environment:
      - APP_POOL=blue
      - RELEASE_ID=release-blue-aws-1.0
      - PORT=3000
    restart: unless-stopped

  app_green:
    image: yimikaade/wonderful:latest
    environment:
      - APP_POOL=green
      - RELEASE_ID=release-green-aws-1.0
      - PORT=3000
    restart: unless-stopped
