services:
  nginx:
    image: nginx:alpine
    ports: ["80:80", "8081:8081", "8082:8082"]
    volumes: ["./nginx.conf:/etc/nginx/nginx.conf:ro"]

  app_blue:
    image: yimikaade/wonderful:latest
    environment:
      - APP_POOL=blue
      - RELEASE_ID=blue-simple

  app_green:
    image: yimikaade/wonderful:latest  
    environment:
      - APP_POOL=green
      - RELEASE_ID=green-simple
